CREATE DATABASE IF NOT EXISTS `todo`;
GRANT ALL ON `todo_test`.* TO 'root'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS `todo_test`;
GRANT ALL ON `todo_test`.* TO 'root'@'%';
FLUSH PRIVILEGES;
